[theme]
primaryColor = "#0072C6"            # RSM blue (main accent)
backgroundColor = "#f7f9fb"         # Very light gray (background)
secondaryBackgroundColor = "#e6f2ff" # Light blue (cards, sidebars)
textColor = "#222222"               # Almost black (text)
font = "monospace"